# Generated by Django 3.1.5 on 2021-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
