# Generated by Django 3.1.5 on 2021-02-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210205_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='core.profile'),
        ),
    ]
