# Generated by Django 3.1.5 on 2021-02-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210205_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_coins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='league_prize',
            field=models.BooleanField(default=False),
        ),
    ]
