# Generated by Django 3.1.5 on 2021-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210205_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_level',
            field=models.IntegerField(default=100),
        ),
    ]
