# Generated by Django 3.1.5 on 2021-02-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210206_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_random',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
