# Generated by Django 3.1.5 on 2021-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_is_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=355, unique=True),
        ),
    ]
