# Generated by Django 3.1.5 on 2021-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210311_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(max_length=455),
        ),
    ]
